vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        strip_images:
            uri_prefix: /images/strip
            upload_destination: '%kernel.project_dir%/public/images/strip'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
